apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: cgahiu-q1  
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-credentials-secret
            key: credentials.json
            namespace: argocd
