apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/helm-values-file: ../dev/values-dev.yaml
    argocd-image-updater.argoproj.io/image-list: nodejs-express-app=europe-west1-docker.pkg.dev/cgahiu-q1/cgahiu-repo/nodejs-express-app
    argocd-image-updater.argoproj.io/nodejs-express-app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/nodejs-express-app.helm.tag: image.tag
    argocd-image-updater.argoproj.io/nodejs-express-app.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{"argocd-image-updater.argoproj.io/image-list":"nodejs-express-app=europe-west1-docker.pkg.dev/cgahiu-q1/cgahiu-repo/nodejs-express-app","argocd-image-updater.argoproj.io/nodejs-express-app.helm.image-name":"image.repository","argocd-image-updater.argoproj.io/nodejs-express-app.helm.tag":"image.tag","argocd-image-updater.argoproj.io/nodejs-express-app.update-strategy":"semver","argocd-image-updater.argoproj.io/write-back-method":"git","notifications.argoproj.io/subscribe.on-sync-failed.slack":"#argocd-img-updater","notifications.argoproj.io/subscribe.on-sync-running.slack":"#argocd-img-updater","notifications.argoproj.io/subscribe.on-sync-succeeded.slack":"argocd-img-updater","notified.notifications.argoproj.io":"{\"on-sync-succeeded:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:slack:argocd-img-updater\":1726963488}"},"creationTimestamp":"2024-09-21T00:21:41Z","finalizers":["resources-finalizer.argocd.argoproj.io"],"generation":846,"labels":{"key":"value"},"name":"nodejs-express-app","namespace":"argocd","resourceVersion":"7360664","uid":"5e2cc38e-8106-4d33-802e-56d1207cb728"},"spec":{"destination":{"namespace":"nodejs-dev","server":"https://kubernetes.default.svc"},"project":"default","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true}}},"status":{"controllerNamespace":"argocd","health":{"status":"Healthy"},"history":[{"deployStartedAt":"2024-09-21T01:27:51Z","deployedAt":"2024-09-21T01:27:51Z","id":2,"initiatedBy":{"automated":true},"revision":"edc382455f4f0ace42adc2c1444bb029211c9f93","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T01:39:51Z","deployedAt":"2024-09-21T01:39:51Z","id":3,"initiatedBy":{"automated":true},"revision":"d1aa7b634e4ee4f5785a860e3dacd9185e6273f6","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T01:45:51Z","deployedAt":"2024-09-21T01:45:51Z","id":4,"initiatedBy":{"automated":true},"revision":"157e7ea34fee168c3ef9ae427dbc8c51dac429bc","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T02:15:51Z","deployedAt":"2024-09-21T02:15:51Z","id":5,"initiatedBy":{"automated":true},"revision":"bbfad32fffe00c1751ed36dd73b5a27307983019","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T03:06:39Z","deployedAt":"2024-09-21T03:06:40Z","id":6,"initiatedBy":{"username":"admin"},"revision":"595cde0ed21d3ba5c26db4e2bef3bca1e49268ac","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T15:09:50Z","deployedAt":"2024-09-21T15:09:52Z","id":7,"initiatedBy":{"username":"admin"},"revision":"c8024e80279405a9f7e40ad499372adbdffa29ca","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T23:04:47Z","deployedAt":"2024-09-21T23:04:49Z","id":8,"initiatedBy":{"username":"admin"},"revision":"9a6b657aa240e7e28f5155c1a234af026806e82f","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T23:37:24Z","deployedAt":"2024-09-21T23:37:25Z","id":9,"initiatedBy":{"username":"admin"},"revision":"9a6b657aa240e7e28f5155c1a234af026806e82f","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T23:37:51Z","deployedAt":"2024-09-21T23:37:51Z","id":10,"initiatedBy":{"username":"admin"},"revision":"9a6b657aa240e7e28f5155c1a234af026806e82f","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},{"deployStartedAt":"2024-09-21T23:59:11Z","deployedAt":"2024-09-21T23:59:11Z","id":11,"initiatedBy":{"username":"admin"},"revision":"9a6b657aa240e7e28f5155c1a234af026806e82f","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}}],"operationState":{"finishedAt":"2024-09-21T23:59:11Z","message":"successfully synced (all tasks run)","operation":{"initiatedBy":{"username":"admin"},"retry":{},"sync":{"revision":"9a6b657aa240e7e28f5155c1a234af026806e82f","syncStrategy":{"hook":{}}}},"phase":"Succeeded","startedAt":"2024-09-21T23:59:11Z","syncResult":{"resources":[{"group":"","hookPhase":"Running","kind":"Service","message":"service/nodejs-express-app-svc unchanged","name":"nodejs-express-app-svc","namespace":"nodejs-dev","status":"Synced","syncPhase":"Sync","version":"v1"},{"group":"apps","hookPhase":"Running","kind":"Deployment","message":"deployment.apps/nodejs-express-app unchanged","name":"nodejs-express-app","namespace":"nodejs-dev","status":"Synced","syncPhase":"Sync","version":"v1"}],"revision":"9a6b657aa240e7e28f5155c1a234af026806e82f","source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}}},"reconciledAt":"2024-09-22T00:09:48Z","resources":[{"health":{"status":"Healthy"},"kind":"Service","name":"nodejs-express-app-svc","namespace":"nodejs-dev","status":"Synced","version":"v1"},{"group":"apps","health":{"status":"Healthy"},"kind":"Deployment","name":"nodejs-express-app","namespace":"nodejs-dev","status":"Synced","version":"v1"}],"sourceType":"Helm","summary":{"images":["europe-west1-docker.pkg.dev/cgahiu-q1/cgahiu-repo/nodejs-express-app:1.0.20240921053046"]},"sync":{"comparedTo":{"destination":{"namespace":"nodejs-dev","server":"https://kubernetes.default.svc"},"source":{"helm":{"valueFiles":["../dev/values-dev.yaml"]},"path":"deploy/helm","repoURL":"git@github.com:xokacar/cgahiu.git","targetRevision":"main"}},"revision":"9a6b657aa240e7e28f5155c1a234af026806e82f","status":"Synced"}}}
    notifications.argoproj.io/subscribe.on-sync-failed.slack: '#argocd-img-updater'
    notifications.argoproj.io/subscribe.on-sync-running.slack: '#argocd-img-updater'
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd-img-updater
    notified.notifications.argoproj.io: '{"on-sync-succeeded:[0].zxM90Et6k4Elb1-fHdjtDJq0xR0:slack:argocd-img-updater":1727023373}'
  creationTimestamp: "2024-09-21T00:21:41Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 1448
  labels:
    key: value
  name: nodejs-express-app
  namespace: argocd
  resourceVersion: "8188751"
  uid: 5e2cc38e-8106-4d33-802e-56d1207cb728
spec:
  destination:
    namespace: nodejs-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - ../dev/values-dev.yaml
    path: deploy/helm
    repoURL: git@github.com:xokacar/cgahiu.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-09-22T13:51:36Z"
    deployedAt: "2024-09-22T13:51:37Z"
    id: 30
    initiatedBy:
      automated: true
    revision: a7802512043992df6fbb196ddfeea195ce592ddc
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T13:54:51Z"
    deployedAt: "2024-09-22T13:54:52Z"
    id: 31
    initiatedBy:
      automated: true
    revision: 035362192c74b76a170045b0d935c464f6ef3bd5
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T14:00:37Z"
    deployedAt: "2024-09-22T14:00:38Z"
    id: 32
    initiatedBy:
      automated: true
    revision: cca2f177f5ee8856203be84dd387020d2926f2fc
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T14:03:51Z"
    deployedAt: "2024-09-22T14:03:52Z"
    id: 33
    initiatedBy:
      automated: true
    revision: f1bb5936af8232a8ebbe72009c6916227ced6117
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T14:09:37Z"
    deployedAt: "2024-09-22T14:09:38Z"
    id: 34
    initiatedBy:
      automated: true
    revision: bc353a144123bdeeb6361c0a931e6260cda54d79
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T14:52:34Z"
    deployedAt: "2024-09-22T14:52:35Z"
    id: 35
    initiatedBy:
      username: admin
    revision: bc353a144123bdeeb6361c0a931e6260cda54d79
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T14:56:57Z"
    deployedAt: "2024-09-22T14:56:58Z"
    id: 36
    initiatedBy:
      username: admin
    revision: bc353a144123bdeeb6361c0a931e6260cda54d79
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T14:58:20Z"
    deployedAt: "2024-09-22T14:58:21Z"
    id: 37
    initiatedBy:
      username: admin
    revision: bc353a144123bdeeb6361c0a931e6260cda54d79
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T15:20:14Z"
    deployedAt: "2024-09-22T15:20:15Z"
    id: 38
    initiatedBy:
      username: admin
    revision: bc353a144123bdeeb6361c0a931e6260cda54d79
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  - deployStartedAt: "2024-09-22T16:42:51Z"
    deployedAt: "2024-09-22T16:42:52Z"
    id: 39
    initiatedBy:
      automated: true
    revision: 90618139a9c5175586671ac86001d80332e0075c
    source:
      helm:
        valueFiles:
        - ../dev/values-dev.yaml
      path: deploy/helm
      repoURL: git@github.com:xokacar/cgahiu.git
      targetRevision: main
  operationState:
    finishedAt: "2024-09-22T16:42:52Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 90618139a9c5175586671ac86001d80332e0075c
    phase: Succeeded
    startedAt: "2024-09-22T16:42:51Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/nodejs-express-app-svc unchanged
        name: nodejs-express-app-svc
        namespace: nodejs-dev
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/nodejs-express-app configured
        name: nodejs-express-app
        namespace: nodejs-dev
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/nodejs-express-app-hpa configured
        name: nodejs-express-app-hpa
        namespace: nodejs-dev
        status: Synced
        syncPhase: Sync
        version: v2
      revision: 90618139a9c5175586671ac86001d80332e0075c
      source:
        helm:
          valueFiles:
          - ../dev/values-dev.yaml
        path: deploy/helm
        repoURL: git@github.com:xokacar/cgahiu.git
        targetRevision: main
  reconciledAt: "2024-09-22T20:36:49Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: nodejs-express-app-svc
    namespace: nodejs-dev
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: nodejs-express-app
    namespace: nodejs-dev
    status: Synced
    version: v1
  - group: autoscaling
    health:
      message: recommended size matches current size
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: nodejs-express-app-hpa
    namespace: nodejs-dev
    status: Synced
    version: v2
  sourceType: Helm
  summary:
    images:
    - europe-west1-docker.pkg.dev/cgahiu-q1/cgahiu-repo/nodejs-express-app:1.0.41
  sync:
    comparedTo:
      destination:
        namespace: nodejs-dev
        server: https://kubernetes.default.svc
      source:
        helm:
          valueFiles:
          - ../dev/values-dev.yaml
        path: deploy/helm
        repoURL: git@github.com:xokacar/cgahiu.git
        targetRevision: main
    revision: 90618139a9c5175586671ac86001d80332e0075c
    status: Synced
